services:
  - type: web
    name: vivek-cyber-expert
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: python bot.py

    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: OWNER_CHAT_ID
        sync: false

      - key: DATA_DIR
        value: data

      - key: DB_PATH
        value: bot.db
